package save_load.tests;


import java.io.*;

import org.junit.Test;

import common.items.Item;
import common.map.IMap;
import common.mocks.MockMap;
import game.Game;
import items.itemList.MassiveGun;
import map.Map;
import player.Player;
import save_load.SaveLoad;

public class SaveLoadTests {
	
	private Map m;
	private String name = "Thomas";
	private int xLocation = 100;
	private int yLocation = 100;
	private Player player = new Player(name, xLocation, yLocation);

	private Game game = new Game();
	
	
	/**
	 * This function is responsible for testing if saving works, 
	 * by picking up and item and saving the file. 
	 * The outcome will be compared with a serialized file which
	 * produced by saving the actual game, then this test will
	 * produce another version by test case and the comparing the
	 * actual saved file which generated by game and saved file which
	 * generated by this test case
	 * 
	 * If both file are equal that saving is working and test is passed
	 * If NOT means the saving is not working as it intended to be.
	 * 
	 */
	@Test
	public void testSaving() {
		
		
		// make a temporary file 
		// insert a player with specific coordinate
		player = new Player(name, xLocation, yLocation);
		IMap m = new MockMap();
		// insert an item with specific coordinate next to the player
		Item i = new MassiveGun();
		m.placeItem(i, 100, 100);
				
		SaveLoad svl = new SaveLoad();
		svl.saveGame(game, "C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\testCaseSaving");
			
		
		//FileInputStream file1 = new InputStream("C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\testCaseSaving.dat");
        //FileInputStream file2 = new InputStream("C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\TestSaving.dat");
        
		//if( //Two file is same that means saving is working){
		//	if NOT means it is not working
			
		//}else{
			
		//}
		
	}

	
	/**
	 * Loading test needs to be changed
	 */
	@Test
	public void loadGame() {
		// make a temporary file 
				// insert a player with specific coordinate
				player = new Player(name, xLocation, yLocation);
				IMap m = new MockMap();
				// insert an item with specific coordinate next to the player
				Item i = new MassiveGun();
				m.placeItem(i, 100, 100);
						
				SaveLoad svl = new SaveLoad();
				svl.saveGame(game, "C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\testCaseSaving");
					
				
				//FileInputStream file1 = new InputStream("C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\testCaseSaving.dat");
		        //FileInputStream file2 = new InputStream("C:\\Users\\Mansour\\Desktop\\SWEN222PROJECTSNICKETYSNACKS\\TestSaving.dat");
		        
				//if( //Two file is same that means saving is working){
				//	if NOT means it is not working
					
				//}else{
					
				//}
		
	}

}
